version: "3.8"

services:
  discordbot:
    env_file:
      - .env
    image: dicord-bot:dev
    environment:
      TOKEN1: ${Token1}
      MyID: ${MyID}
    build:
      context: .
      dockerfile: Dockerfile
      # target: dev
    container_name: useless-bot
    restart: always
    # ports:
    #   - "80:80"
    # volumes:
    #   - ./config:/ygopro-server/config
    #   - ./patch:/ygopro-server/ygopro/patch
    #   - ./manual:/ygopro-server/ygopro/manual
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
